### PR TITLE
Upgrade libp2p to v0.24.1

### PR DESCRIPTION
**Pull request by mauromorales**
This PR upgrades lib2p2 to the latest version. There were some incompatibility changes between 0.23 and 0.24. But it seems edgevpn was minimally affected.

### CODE REVIEW

**Comment by mudler** [comment]
It looks there is some regression with v0.24.x as tests starts to fail badly when bumping to it.  I'd consider opening up an issue upstream, as maintainers are friendly and very receptive, better would be to get as much as log as possible with debug loglevel (for both libp2p and edgevpn).

They already know about us as I did sparely helped when facing issues (see e.g. https://github.com/libp2p/go-libp2p/issues/1319 ), but if we can give them more details that'd be really prefered.

@vyzo: hey :wave: seems you are now working more on lotus, but does this ring a bell? maybe cc: @marten-seemann @MarcoPolo is there something non-obvious I'm not catching with 0.24? connections become quite fragile with 0.24.x here

**Comment by marten-seemann** [comment]
> @vyzo: hey 👋 seems you are now working more on lotus, but does this ring a bell? maybe cc: @marten-seemann @MarcoPolo is there something non-obvious I'm not catching with 0.24? connections become quite fragile with 0.24.x here. errors reminds me when we first switched in favor of rcmgr. Thanks for any advice! 🙏

What do you mean by "connections become quite fragile"?

**Comment by mudler** [comment]
> > @vyzo: hey wave seems you are now working more on lotus, but does this ring a bell? maybe cc: @marten-seemann @MarcoPolo is there something non-obvious I'm not catching with 0.24? connections become quite fragile with 0.24.x here. errors reminds me when we first switched in favor of rcmgr. Thanks for any advice! pray
> 
> What do you mean by "connections become quite fragile"?

I apologize @marten-seemann as I don't have enough data points as for now, but there is a notable huge diff in our test matrix:

- This is current master  text matrix https://github.com/mudler/edgevpn/actions/runs/3788749847 , pinned at libp2p  v0.23.4, which almost is always successfull (some time there are hiccups, as some e2e are flaky, but still you can see from the history the builds are almost successfull)
- This is when bumping to v0.24.x https://github.com/mudler/edgevpn/actions/runs/3759115514 . generally, any runs I've tried out where ending similarly (tests in the same host are successfull, but on remote hosts they just fails, sporadically they are green)

@mauromorales can we try to collect more data maybe with debug logging? problem is that logs from CI tends to be huge then, so it's hard to spot down issues.

**Comment by mauromorales** [comment]
Sure thing, I'll try to gather some data points and get back to you all

**Comment by mudler** [comment]
Things seems to be back to normal with libp2p 0.25.1 : #51

**Comment by mauromorales** [comment]
awesome, closing this one

**Pull request closed without merging**
