### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by reneleonhardt**
### Features
* Update Go dependencies
* Update Javascript dependencies
* Update Makefile dependencies
* Build/test/release with Go 1.22 (you could add a matrix or I could revert it 😅)
* Configure Dependabot to update go.mod, .gitmodules and GitHub Actions

### CODE REVIEW

**Comment by reneleonhardt** [comment]
@mudler Can you run the GitHub Actions? I can't update LocalAI without a new edgevpn release 🤷

**Review by mudler — APPROVED** [review]
Lovely! thanks @reneleonhardt !

**Comment by mudler** [comment]
ouch, one more left: 

```
Error: pkg/discovery/dht.go:175:61: p.Pretty undefined (type peer.ID has no field or method Pretty)
```

**Comment by reneleonhardt** [comment]
> ouch, one more left:
> 
> ```
> Error: pkg/discovery/dht.go:175:61: p.Pretty undefined (type peer.ID has no field or method Pretty)
> ```

Hmm local build didn't catch that... if you can, provide a Makefile for macOS and Linux developers to easily run workflows locally 😅

**Pull request merged**
